#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'drush',
  :git => "https://github.com/proviso/erikwebb-drush",
  :ref => "1-manage-usr-share-drush"
mod "mysql5",
  :git => "https://github.com/zivtech/puppet-mysql5"
mod "php53",
  :git => "https://github.com/zivtech/puppet-php53",
  :ref => "29dcf34bd776355f3c800ebd2bd7a530ffa177fa"
mod "solr",
  :git => "https://github.com/zivtech/puppet-drupal-solr"
mod "vcsrepo",
  :git => "https://github.com/bruce/puppet-vcsrepo"
mod "webadmin",
  :git => "https://github.com/zivtech/puppet-webadmin",
  :ref => "c25a220f7a76386a86d75e5cd8b17c18ab81b4c3"

mod "thomasvandoren/redis"
